apiVersion: v1
kind: Pod
metadata:
   name: mysql
   labels:
     app: mysql
spec:
  containers:
     - name: mysql
       image: mysql:5.7
       ports:
         - containerPort: 3306
           name: mysql
           protocol: TCP
       env:
         - name: MYSQL_ROOT_PASSWORD
           value: ocs
       volumeMounts:
         - mountPath: /var/lib/mysql
           name: mysqlvolume
  volumes:
    - name: mysqlvolume
      hostPath:
          path: /opt/mysql
