apiVersion: apps/v1beta1
kind: Deployment
metadata:
   name: ocsserverdepl
spec:
  replicas: 3
  template:
    metadata:
       labels:
         app: ocsserver
    spec:
      containers:
        - name: ocsserver
          image: sandeepchowdary/ocs:2.3
          env:
           - name: OCS_DBNAME
             value: ocsweb
           - name: OCS_DBUSER
             value: ocs
           - name: OCS_DBPASS
             value: ocs
#           - name: OCS_DBSERVER_READ
#             value: 10.105.6.77
#           - name: OCS_DBSERVER_WRITE
#             value: 10.105.6.77

          ports:
            - containerPort: 80
