apiVersion: v1
kind: Service
metadata:
   name: red
spec:
  selector:
      app: ocsserver
  type: NodePort
  ports:
    - name: ocshttp
#      nodePort: 80
      port: 80
      targetPort: 80
      protocol: TCP
